Category List Implementation
tryber/sd-08-project-frontend-online-store pull request #223
Opened 2021-01-28 23:28 UTC by luizfrodrigues

Implementação da Lista de categorias.

2021-01-29 08:53 UTC, NicolasGodek requested changes
gostei da solução, porém acho que se der merge assim não vai passar ESLint não passar

2021-01-29 08:53 UTC, NicolasGodek commented on src/components/CategoryList.js
> +export default CategoryList;
Tente adicionar uma linha no fim para o eslint não reclamar.

2021-01-29 15:42 UTC, MuriloBatista commented on src/App.js
> +          <Route path="/" component={ CategoryList } />
Não seria o componente `CategoryList` renderizado dentro de `SearchBar`? Se sim, nesse caso, acredito não ser necessário declarar uma rota, já que ele é um componente que sempre estará renderizado dentro da Pagina inicial.

2021-01-29 17:19 UTC, luizfrodrigues commented on src/components/CategoryList.js
> +export default CategoryList;
Anotado.

2021-01-29 17:20 UTC, luizfrodrigues commented on src/App.js
> +          <Route path="/" component={ CategoryList } />
Obrigado pelo retorno. Estávamos tentando visualizar se o requisito estava funcionando. Agora vamos tentar essa aboradagem.

2021-01-30 18:34 UTC, NicolasGodek approved these changes

2021-01-30 19:58 UTC, merged