[GRUPO 30][REQUISITO 3]
tryber/sd-08-project-frontend-online-store pull request #293
Opened 2021-01-29 19:17 UTC by caiomzrocha

2021-01-29 21:14 UTC, dougfer approved these changes

2021-01-29 22:44 UTC, josebejohann requested changes

2021-01-29 22:44 UTC, josebejohann commented on src/App.js
> +        <Route path="/shoppingcart" component={ ShoppingCart } exact />
Fala, Caião!
Nesse caso aqui, acredito que o atributo `exact` não seja necessário, já que o `path` do componente é bem definido.

2021-01-29 22:44 UTC, josebejohann commented on src/App.js
> +import ShoppingCart from './pages/ShoppingCart';
Que tal se os `imports` das páginas ficarem todos numa mesma linha? Acredito que o código ficaria mais limpo. =)
Ficaria assim:
`import { ProductsList, ShoppingCart } from './pages';`

2021-01-29 23:12 UTC, caiomzrocha commented on src/App.js
> +        <Route path="/shoppingcart" component={ ShoppingCart } exact />
Beleza, vou remover aqui.

2021-01-30 18:19 UTC, caiomzrocha commented on src/App.js
> +import ShoppingCart from './pages/ShoppingCart';
Não sabia que dava para fazer isso, mas tive que criar um outro arquivo para funcionar.

2021-02-01 11:50 UTC, josebejohann approved these changes

2021-02-01 11:50 UTC, merged