[GRUPO 30][REQUISITO 4]
tryber/sd-08-project-frontend-online-store pull request #326
Opened 2021-01-29 21:29 UTC by caiomzrocha

2021-02-01 11:56 UTC, josebejohann requested changes

2021-02-01 11:56 UTC, josebejohann commented on src/pages/CategoryList.js
> +    console.log(categories);
Fala, Caião! Não seria melhor retirar esse `console.log()`?
Código muito bom!

2021-02-01 17:22 UTC, dougfer approved these changes

2021-02-01 17:24 UTC, dougfer approved these changes

2021-02-02 17:55 UTC, caiomzrocha commented on src/pages/CategoryList.js
> +    console.log(categories);
Claro, esqueci de remover antes do push.

2021-02-02 21:39 UTC, josebejohann approved these changes

2021-02-02 21:40 UTC, merged