[GRUPO 30] [REQUISITO 13]
tryber/sd-08-project-frontend-online-store pull request #721
Opened 2021-02-10 00:22 UTC by dougfer

2021-02-10 17:50 UTC, PPiquini commented on src/pages/ProductDetails.js
> +    console.log(cart.length);
Tem um console log aqui

2021-02-10 17:52 UTC, PPiquini commented on src/pages/ProductsList.js
> +    console.log(cart.length);
Outro console log

2021-02-10 17:55 UTC, PPiquini requested changes
Precisa tirar os console logs. Outra coisa também, vc acha que dá pra colocar essa função em um componente pai e passa ela como props para as outras páginas? assim evitaria de repetir a função em cada página. Não tenho certeza se funcionaria corretamente.

2021-02-13 00:29 UTC, caiomzrocha approved these changes

2021-02-13 01:21 UTC, PPiquini approved these changes
Tudo certo!

2021-02-13 01:21 UTC, merged